// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebDashBoard.Data;

#nullable disable

namespace WebDashBoard.Migrations
{
    [DbContext(typeof(ConfigureItemContext))]
    partial class ConfigureItemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ConfigureLib.InvokerConfigItem", b =>
                {
                    b.Property<int>("StartupIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StartupIndex"), 1L, 1);

                    b.Property<string>("Args")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WorkFolder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StartupIndex");

                    b.ToTable("InvokerConfigItem");
                });
#pragma warning restore 612, 618
        }
    }
}
